# Site wide configuration

title: InternetHostage
description: There was a time where the Internet didn't exist
logo: # 120x120 px default image used for Twitter summary card
teaser: # 400x250 px default teaser image used in image archive grid
locale:
url: http://internethostage.com
# Jekyll configuration

sass:
    sass_dir: _sass
    style: compressed
permalink: pretty
paginate: 5
paginate_path: "blog/:num/"
markdown: kramdown
highlighter: rouge
gems:
  - jekyll-sitemap

# Site owner
owner:
  name: Cristian Guerrero
  email: cristian@example.org
  twitter: internethostage
  github: internethostage
  linkedin: guerrerocristian
  gmaps_key: AIzaSyCeMYuMWKen-JvDXk9C92tNnsC7yvBf4vc
  google:
    ad-client:
    ad-slot:
    ads: false
  bio: Ruby on Rails Developer
  avatar: avatar.png # 160x160 px image for author byline
disqus-shortname: leblog-1


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
